APP:
  ENVIRONMENT: sim
  DEBUG: True
  # Only accept True or False

DATABASE:
    USERNAME: testuser
    PASSWORD: testpassword
    HOST: 172.17.0.1
    PORT: 33060
    DB: mytestdb
    ECHO: False

EVALUATOR:
    MAX_TILT: 50
    DELTA_TILT: 1
    MAX_DELTA_USER_THRP_DL_PERCENTAJE: 5.0
    MAX_DELTA_TRAFFIC_DL_PERCENTAJE: 10.0
    MIN_USER_AVG: 80.0
    MAX_USER_AVG: 200.0
