APP:
  # ENVIRONMENT: sim
  ENVIRONMENT: prod
  DEBUG: True
  # Only accept True or False

DB_LOCAL:
    # HOST: 172.17.0.1 # linux
    HOST: 127.0.0.1 # windows
    DATABASE: mytestdb
    USER: testuser
    PASSWORD: testpassword
    PORT: 33060
    ECHO: False

DB_PROD:
    HOST: 10.120.145.103
    DATABASE: db
    USER: vmran
    PASSWORD: Vixsdeod3
    PORT: 3306
    ECHO: False

EVALUATOR:
    MAX_TILT: 50
    DELTA_TILT: 1
    MAX_DELTA_USER_THRP_DL_PERCENTAJE: 5.0
    MAX_DELTA_TRAFFIC_DL_PERCENTAJE: 10.0
    MIN_USER_AVG: 80.0
    MAX_USER_AVG: 200.0
